[versions]
androidxCoreVersion = "1.8.0"
androidxLifecycleVersion = "2.3.1"
androidxActivityComposeVersion = "1.4.1"
composeVersion = "1.1.1"
material3Version = "1.0.0-alpha02"
junitVersion = "4.13.2"
androidxTextExtJunitVersion = "1.1.5"
androidxTestEspressoCoreVersion = "3.5.1"
retrofitVersion = "2.9.0"
kotlinxCoroutinesVersion = "1.5.0"
lifecycleViewmodelKtxVersion = "2.4.0-alpha02"
lifecycleViewmodelComposeVersion = "1.0.0-alpha07"
navigationComposeVersion = "2.5.3"
hiltVersion = "2.39.1"
hiltNavigationComposeVersion = "1.0.0"
mockkVersion = "1.12.0"
kotlinxCoroutinestestVersion = "1.5.2"
coilComposeVersion = "1.3.2"
lottieVersion = "4.2.0"

[libraries]
coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreVersion" }
runtimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycleVersion" }
activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityComposeVersion" }
composeUi = { module = "androidx.compose.ui:ui", version.ref = "composeVersion" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeVersion" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeVersion" }
composeUiTest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeVersion" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3Version" }
junit = { module = "junit:junit", version.ref = "junitVersion" }
testJunit = { module = "androidx.test.ext:junit", version.ref = "androidxTextExtJunitVersion" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspressoCoreVersion" }
composeUiJunit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
retrofitConverter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitVersion" }



coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesVersion" }
lifecycleViewmodel = { module = "oandroidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtxVersion" }
lifecycleViewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelComposeVersion" }
navigationCompose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationComposeVersion" }
hiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion" }
hiltCompiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltVersion" }
hiltNavigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationComposeVersion" }
mockk = { module = "io.mockk:mockk", version.ref = "mockkVersion" }
coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinestestVersion" }
coilCompose = { module = "io.coil-kt:coil-compose", version.ref = "coilComposeVersion" }
lottieCompose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieVersion" }

[bundles]
appDependencies = [
    "coreKtx", "runtimeKtx", "activityCompose", "composeUi",
    "composeUiToolingPreview", "composeUiTooling","composeUiTest","material3","junit","testJunit","espressoCore","composeUiJunit4","retrofit","retrofitConverter",
    "coroutines","lifecycleViewmodel","lifecycleViewmodelCompose","navigationCompose","hiltAndroid","hiltCompiler","hiltNavigation","mockk","coroutinesTest","coilCompose","lottieCompose"]

