name: Detekt Static Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detekt:
    name: Run Detekt
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-includes: |
            caches
            notifications
          gradle-home-cache-cleanup: true

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run Detekt analysis (fast mode)
        run: ./gradlew :app:detekt --no-daemon --parallel --configuration-cache --build-cache --stacktrace

      - name: Upload Detekt report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: |
            app/build/reports/detekt/detekt.html
            app/build/reports/detekt.html
            **/build/reports/detekt*/**/*.html
          if-no-files-found: warn