name: Detekt

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**/*.kt'
      - 'detekt.yml'
      - 'build.gradle*'
      - 'settings.gradle*'
      - 'gradle.properties'
  push:
    branches: [ main, develop ]
    paths:
      - '**/*.kt'
      - 'detekt.yml'
      - 'build.gradle*'
      - 'settings.gradle*'
      - 'gradle.properties'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Solo si mantienes el submódulo; si publicas el JAR, elimina esto
      #- run: ./gradlew :detekt-architecture-rules:jar --build-cache --configuration-cache

      - name: Run Detekt (app only, fast)
        run: ./gradlew :app:detektMain --build-cache --configuration-cache --parallel

      - name: Upload Detekt HTML (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: '**/build/reports/detekt*/**/*.html'
          if-no-files-found: warn