name: Detekt Static Analysis

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**/*.kt'
      - 'detekt.yml'
      - 'build.gradle*'
      - 'gradle.properties'
      - 'settings.gradle*'
      - '.github/workflows/detekt.yml'
  push:
    branches: [ main, develop ]
    paths:
      - '**/*.kt'
      - 'detekt.yml'
      - 'build.gradle*'
      - 'gradle.properties'
      - 'settings.gradle*'
      - '.github/workflows/detekt.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Detect changed files
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            kotlin:
              - '**/*.kt'
              - 'detekt.yml'
              - 'build.gradle*'
              - 'gradle.properties'
              - 'settings.gradle*'

      - name: Skip if nothing relevant changed
        if: steps.changes.outputs.kotlin != 'true'
        run: echo "No Kotlin/Gradle changes. Skipping Detekt." && exit 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run Detekt (parallel)
        run: ./gradlew detekt --stacktrace

      - name: Upload Detekt report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          if-no-files-found: warn
          path: |
            **/build/reports/detekt*/**/*.html