name: Detekt Static Analysis

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**/*.kt'
      - 'detekt.yml'
      - 'build.gradle*'
      - 'gradle.properties'
      - 'settings.gradle*'
      - '.github/workflows/detekt.yml'
  push:
    branches: [ main, develop ]
    paths:
      - '**/*.kt'
      - 'detekt.yml'
      - 'build.gradle*'
      - 'gradle.properties'
      - 'settings.gradle*'
      - '.github/workflows/detekt.yml'

jobs:
  detekt:
    name: Run Detekt
    runs-on: ubuntu-latest
    cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run Detekt analysis
        run: ./gradlew detekt --stacktrace

      - name: Upload Detekt report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: |
            app/build/reports/detekt.html
            app/build/reports/detekt/detekt.html
            **/build/reports/detekt*/**/*.html
          if-no-files-found: warn