- name: Run Unit Tests with Coverage
  run: ./gradlew testDebugUnitTest jacocoDebugReport --no-daemon --parallel

- name: Upload JaCoCo Report
  if: always()
  uses: actions/upload-artifact@v4
  with:
    name: jacoco-report
    path: app/build/reports/jacoco/html